# # # # services:

# # # #   user-service:
# # # #     build: ./user-service
# # # #     ports:
# # # #       - "8081:8081"

# # # #   order-service:
# # # #     build: ./order-service
# # # #     ports:
# # # #       - "8083:8083"
# # # #     depends_on:
# # # #       - user-service



# # # services:

# # #   mysql:
# # #     image: mysql:8
# # #     environment:
# # #       MYSQL_ROOT_PASSWORD: root
# # #       MYSQL_DATABASE: tubesdb
# # #     ports:
# # #       - "3307:3306"

# # #   user-service:
# # #     build: ./user-service
# # #     ports:
# # #       - "8081:8081"
# # #     depends_on:
# # #       - mysql

# # #   order-service:
# # #     build: ./order-service
# # #     ports:
# # #       - "8083:8083"
# # #     depends_on:
# # #       - mysql
# # #       - user-service

# # services:

# #   mysql:
# #     image: mysql:8
# #     environment:
# #       MYSQL_ROOT_PASSWORD: root
# #       MYSQL_DATABASE: tubesdb
# #     ports:
# #       - "3307:3306"

# #   user-service:
# #     build: ./user-service
# #     ports:
# #       - "8081:8081"
# #     environment:
# #       - DB_HOST=mysql
# #     depends_on:
# #       - mysql

# #   order-service:
# #     build: ./order-service
# #     ports:
# #       - "8083:8083"
# #     environment:
# #       - DB_HOST=mysql
# #     depends_on:
# #       - mysql
# #       - user-service



# services:

#   mysql:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: tubesdb
#     ports:
#       - "3307:3306"

#   user-service:
#     build: ./user-service
#     ports:
#       - "8081:8081"
#     depends_on:
#       - mysql
#     environment:
#       DB_HOST: mysql
#       DB_PORT: 3306

#   order-service:
#     build: ./order-service
#     ports:
#       - "8083:8083"
#     depends_on:
#       - mysql
#       - user-service
#     environment:
#       DB_HOST: mysql
#       DB_PORT: 3306


services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tubestahap2

    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  user-service:
    build: ./user-service

    ports:
      - "8081:8081"

    depends_on:
      mysql:
        condition: service_healthy

  order-service:
    build: ./order-service

    ports:
      - "8083:8083"

    environment:
      DB_HOST: mysql
      DB_PORT: 3306

    depends_on:
      mysql:
        condition: service_healthy
